base_link: 'world'

# =====================================================
psm_one_gripper:
    end_effector_name: 'psm_one_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['PSM1/jaw']

    #open position
    pregrasp_posture : [0.523]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.262]
    grasp_time_from_start : 4.0

    end_effector_parent_link: 'PSM1/tool_wrist_sca_shaft_link'

    end_effector_tool_tip_link: 'PSM1/tool_tip_link'

    #normal needle grasping parameters
    theta_normal : [0.004, 0.0, 0.0, 0.0833]

    #grasping parameters limits
    theta_limits : [0.0, 0.005, -1.5708, 1.5708, 0.0, 6.283, 0.0, 3.1415]

    #possible needle grasping search resolution
    theta_resolution : [0.001, 0.2094, 0.2094, 0.2094]
    #theta_resolution : [0.001, 0.2094, 0.1047, 0.2094]

# =====================================================
psm_two_gripper:
    end_effector_name: 'psm_two_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['PSM2/jaw']

    #open position
    pregrasp_posture : [0.0095]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [-0.0125]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.15, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'PSM2/tool_wrist_sca_shaft_link'

    end_effector_tool_tip_link: 'PSM2/tool_tip_link'

    #normal needle grasping parameters
    theta_normal : [0.004, 0.0, 0.0, 0.083]

    #grasping parameters limits
    theta_limits : [0.0, 0.005, -1.5708, 1.5708, 0.0, 6.283, 0.0, 3.1415]

    #possible needle grasping search resolution
    theta_resolution : [0.001, 0.2094, 0.1047, 0.2094]

